name : run node application
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 20.x
        uses: actions/setup-node@v2
        with:
          node-version: '20'
      - name : test node application
      - name : install dependencies and run testsy
        run: npm install
      - name : run test cases        
        run: npm ci
      - name : build node application
        run: npm run build
      - name : run node application
        run: node dist/index.js